
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

public class MapFrame extends javax.swing.JFrame {

    private URL url;
    private ImageIcon icon;
    private String source;
    private String destination;
    private String[] waypoints;
    double lat = 44.439663;
    double lon = 26.096306;
    int zoom = 12;

    /**
     * Creates new form NewJFrame
     *
     * @param source
     * @param destination
     * @param waypoints
     */
    public MapFrame(String source, String destination, String[] waypoints) {
        initComponents();
        this.source = source;
        this.destination = destination;
        this.waypoints = waypoints;
        createMap();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 760));
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(139, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 60, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createMap() {

        lat = 44.439663;
        lon = 26.096306;
        
        try {
            url = new URL("https://maps.googleapis.com/maps/api/staticmap?"
                    + "center=" + lat + "," + lon + "&"
                    + "zoom=" + zoom + "&"
                    + "size=800x500&maptype=roadmap&"
                    + "key=AIzaSyBPdzxz3LQzNkM5u3Fcn-4wvdxOWFEDK9g");
        } catch (MalformedURLException ex) {
            Logger.getLogger(MapFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            icon = new ImageIcon(ImageIO.read(url).getScaledInstance(1000, 600, java.awt.Image.SCALE_SMOOTH));
        } catch (IOException ex) {
            Logger.getLogger(MapFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        jLabel1.setIcon(icon);

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
